In [4]:
import pandas as pd
from pycaret.classification import*
from pycaret.regression import*

In [3]:
df = pd.read_csv('../Data/bitcoin_USD_close_data-2017-02-09_2018-02-09.csv')
df.head()

             Date    Price
0   2/9/2017 0:00   988.95
1  2/10/2017 0:00   993.08
2  2/11/2017 0:00  1010.00
3  2/12/2017 0:00   999.51
4  2/13/2017 0:00   996.86

In [5]:
experiement = setup(df, target='Price',session_id=123)

In [6]:
best_model = compare_models()

Processing:   0%|          | 0/77 [00:00<?, ?it/s]

In [11]:
predict_model(best_model,df.sample(10))

                Date         Price  prediction_label
59     4/9/2017 0:00   1210.050049       5120.935814
309  12/15/2017 0:00  17601.939453       5120.935814
9     2/18/2017 0:00   1058.410034       5120.935814
299   12/5/2017 0:00  11696.059570       5120.935814
242   10/9/2017 0:00   4772.970215       5120.935814
156   7/15/2017 0:00   1993.260010       5120.935814
170   7/29/2017 0:00   2720.080078       5120.935814
79    4/29/2017 0:00   1327.040039       5120.935814
165   7/24/2017 0:00   2779.040039       5120.935814
231   9/28/2017 0:00   4185.290039       5120.935814

In [13]:
save_model(best_model, model_name='Light Gradient Boosting Machine')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('numerical_imputer',
                  TransformerWrapper(include=[], transformer=SimpleImputer())),
                 ('categorical_imputer',
                  TransformerWrapper(include=['Date'],
                                     transformer=SimpleImputer(strategy='most_frequent'))),
                 ('rest_encoding',
                  TransformerWrapper(include=['Date'],
                                     transformer=TargetEncoder(cols=['Date'],
                                                               handle_missing='return_nan'))),
                 ('trained_model', LGBMRegressor(n_jobs=-1, random_state=123))]),
 'Light Gradient Boosting Machine.pkl')